/*               "Copyright 2020 Infosys Ltd.
               Use of this source code is governed by GPL v3 license that can be found in the LICENSE file or at https://opensource.org/licenses/GPL-3.0
               This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License version 3"*/
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'displayName'
})
export class DisplayNamePipe implements PipeTransform {
  transform(value: string, args?: any): any {
    let name = '';
    switch (value.toLowerCase()) {
      case 'automationcentral':
        name = 'Tools';
        break;
      case 'autogeneratedtopic':
        name = 'Topics';
        break;
      case 'kshopdocument':
        name = 'Kshop Document';
        break;
      case 'project':
        name = 'Project References';
        break;
      case 'kshop':
        name = 'Documents';
        break;
      case 'itemtype':
        name = 'Item Type';
        break;
      case 'authors.mailid':
        name = 'Authors';
        break;
      case 'mstlocation':
        name = 'Location';
        break;
      case 'status':
        name = 'Project Status';
        break;
      case 'marketing':
        name = 'Marketing';
        break;
      default:
        name = value;
        break;
    }
    return name;
  }
}
